os: linux

dist: xenial

sudo: false

language: node_js

node_js:
  - '8'
  - '10'
  - '11'
  - '12'
  - 'lts/*'

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        chrome: stable
        firefox: latest
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless
      script:
        - npm run travis
    # NOTE: https://github.com/karma-runner/karma-safari-launcher/issues/29
    # - os: osx
    #   osx_image: xcode10.2
    #   node_js:
    #     - 'lts/*'
    #   env:
    #     - BROWSERS=Safari
    #   script:
    #     - npm run travis
    - os: osx
      osx_image: xcode10.1
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=Safari
      script:
        - npm run travis
    - os: osx
      osx_image: xcode9.2
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=Safari
      script:
        - npm run travis

git:
  depth: 3

cache: npm

script:
  - npm run lint
  - npm run mocha
  - npm run build
