os: linux

dist: xenial

sudo: false

language: node_js

node_js:
  - '8'
  - '10'
  - '12'
  - 'lts/*'

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        chrome: stable
        firefox: latest
      node_js:
        - 'lts/*'
      script:
        - yarn add -D karma-chrome-launcher karma-firefox-launcher
        - yarn karma start --single-run --browsers ChromeHeadlessNoSandbox,FirefoxHeadless
    # NOTE: https://github.com/karma-runner/karma-safari-launcher/issues/29
    # - os: osx
    #   osx_image: xcode10.2
    #   node_js:
    #     - 'lts/*'
    #   script:
    #     - yarn add -D karma-safari-launcher
    #     - yarn karma start --single-run --browsers Safari
    - os: osx
      osx_image: xcode10.1
      node_js:
        - 'lts/*'
      script:
        - yarn add -D karma-safari-launcher
        - yarn karma start --single-run --browsers Safari
    - os: osx
      osx_image: xcode9.2
      node_js:
        - 'lts/*'
      script:
        - yarn add -D karma-safari-launcher
        - yarn karma start --single-run --browsers Safari

git:
  depth: 3

cache: yarn

script:
  - yarn run lint
  - yarn run test
  - yarn run check-types
